version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-casino-v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: casino
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"